config/routes.rb
Sample::Application.routes.draw do

  require 'subdomain'

  #resources :users, :only => :show
  resources :roles
  devise_for :users

  root 'home#index'


constraints(Subdomain) do
  match '/' => 'home#index', :via => [:get]
end

#match '/' => 'home#index', :constraints => { :subdomain => 'www' }, :via => [:get]
match '/' => 'profiles#show', :constraints => { :subdomain => /.+/ }, :via => [:get]


  #get "profiles/show"
  #get "home/index"

end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


#validates_format_of :name, with: /^[a-z0-9_]+$/, message: "must be lowercase alphanumerics only"

#validates_length_of :name, maximum: 32, message: "exceeds maximum of 32 characters"

#validates_exclusion_of :name, in: ['www', 'mail', 'ftp'], message: "is not available"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  include UrlHelper
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def main_subdomain_url(subdomain, extras = {})
    if current_user
      root_url(extras.merge(:subdomain => subdomain))
    else
      new_user_session_url(extras.merge(:subdomain => subdomain))
    end
  end

  def after_sign_in_path_for(resource, extras = {})
    if current_user.present?
      main_subdomain_url(current_user.name, extras)
    end
  end

  def after_sign_out_path_for(resource, extras = {})

      main_subdomain_url(false, extras)

  end

  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name,:email, :password, :password_confirmation, :role) }
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:name,:email, :password, :password_confirmation, :role)
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def show
     @user = User.where(:name => request.subdomain).first || not_found
  end

  def not_found
    raise ActionController::RoutingError.new('User Not Found')
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_filter :authenticate_user!
 
  def show
     @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def with_subdomain(subdomain)
    subdomain = (subdomain || "")
    subdomain += "." unless subdomain.empty?
    [subdomain, request.domain, request.port_string].join
  end
  
  def url_for(options = nil)
    if options.kind_of?(Hash) && options.has_key?(:subdomain)
      options[:host] = with_subdomain(options.delete(:subdomain))
    end
    super
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!--   
<%#@users.each do |user| %>
<%#= user.name %> 
<%#= link_to root_url(:subdomain => user.name), root_url(:subdomain => user.name) %>
<%#end %>
   -->

<div ng-controller="IndexCtrl">
   <h1 class="text-center">Sample Application</h1>

	<h2>{{ title }}</h2>
  <p>{{ content }}</p>
	</br>
</div>

	

app/views/layouts/_navigation.html.erb
<!-- <%#= link_to "sample-app", root_path, :class => 'brand' %>
 <ul class="nav">
  <li>
    <%#= link_to 'sample-app', root_url(:host => request.domain) %>
  </li> -->
 <!--  <%# if request.subdomain.present? && request.subdomain != "www" %>
    <%#if user_signed_in? %>
      <li>
        <%#= link_to 'Edit account', edit_user_registration_url %>
      </li>
      <li>
        <%#= link_to 'Logout', destroy_user_session_url, :method=>'delete' %>
      </li>
    <%# else %>
      <li>
        <%#= link_to 'Login', new_user_session_url %>
      </li>
    <%# end %>
  <%# else %>
    <li>
      <%#= link_to 'Sign up', new_user_registration_url(:host => request.domain) %>
    </li>
    <#% if user_signed_in? %>
      <li>
        <#%= link_to 'Logout', destroy_user_session_url, :method=>'delete' %>
      </li>
    <#% end %>
  <#% end %>
 </ul>


 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  ng-app>
<head>
  <title style="padding-left:10px;">Sample-App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%#= link_to "sample-app", root_path, :class => 'brand' %>
    <ul class="nav">

      <%#= link_to 'main', root_url(:host => request.domain) %>


     <% if request.subdomain.present? && request.subdomain != "www" %>
      <%if user_signed_in? %>
        <li>
          <%= link_to 'Edit account', edit_user_registration_url %>
        </li>
        <li>
          <%= link_to 'Logout', destroy_user_session_url, :method=>'delete' %>
        </li>
      <% end %>
    <% else %>

        <%#= link_to 'Sign up', new_user_registration_url(:host => request.domain) %>

      <% if user_signed_in? %>
        <li>
          <%= link_to 'Logout', destroy_user_session_url, :method=>'delete' %>
        </li>
      <% end %>
    <% end %>
   </ul>



  <%= yield %>


</div>
</body>
</html>

app/views/profiles/show.html.erb
<h1>User-Profile</h1>
<h3><%= @user.name %></h3>
<h3><%= @user.email %></h3>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/users/show.html.erb
<p>User Details</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Profile: <%= link_to root_url(:subdomain => @user.name), root_url(:subdomain => @user.name) %></p>